# Generated by Django 2.1.4 on 2020-07-23 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(default=None, upload_to='videos/'),
            preserve_default=False,
        ),
    ]
