# Generated by Django 2.1.4 on 2020-07-23 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video',
        ),
    ]
